name: Django CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.10.13]

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub 
        if: ${{ env.DOCKER_USERNAME }}
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies inside Docker container
        run: |
          docker run --rm python:${{ matrix.python-version }}-slim pip install --upgrade pip
          docker run --rm -v $(pwd):/app python:${{ matrix.python-version }}-slim pip install -r requirements.txt

      - name: Build Docker image 
        run: |
          docker build -t app .

      - name: Run Tests inside Docker container
        run: |
          docker run -it --rm app python manage.py test

      - name: Push Docker image to registry
        if: ${{ env.DOCKER_USERNAME }}
        run: |
          docker push atodekimeru/myproject
