name: Update issue status

on:
  - push
  - pull_request

jobs:
  update-issue-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get issue information
        uses: actions/github-script@v5
        id: issue_info
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            return issue.data;

      - name: Get current branch
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Update issue status to Done if in develop branch
        if: ${{ steps.get_branch.outputs.branch == 'develop' }}
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue_info.outputs.number }},
              state: "closed",
              labels: ['Done']
            });

      - name: Update issue status to In progress if in main branch
        if: ${{ steps.get_branch.outputs.branch == 'main' }}
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue_info.outputs.number }},
              state: "open",
              labels: ['In progress']
            });